### ISSUE TITLE
ItemHandler.getGrassJsonのnull判定がおかしい

### ISSUE THREAD

**Issue by ecilavip** [GrassLife/GrassItem#2]
```Java
return uniqueName == null ? getVanillaGrassJson(item) : getGrassJson(item, uniqueName);
```
って部分、ItemHandler.getNBTStringがnull返すことないからちょっとおかしい気がする

**Comment by ghost** [comment]
ItemHandler.getNBTStringは値を
`return nbtTag == null || !nbtTag.hasKey(key) ? null : nbtTag.get(key).toString();`
のように返すので、nullである可能性もあります

**Comment by ecilavip** [comment]
たし:crab:
