### ISSUE TITLE
ItemHandler.getGrassJson(String uniqueName)が欲しい

### ISSUE THREAD

**Issue by ecilavip** [GrassLife/GrassItem#4]
`getGrassJson(null, "hogehoge")`って呼び出すのちょっとバカっぽい気がした

**Comment by ecilavip** [comment]
ここは #3 と絡むので #3 解決後でいいかなという感じ

**Comment by ghost** [comment]
ItemHandler.getGrassJson(uniqueName)を追加するとなると、ItemHandlerはItemを扱うというよりもJsonを扱うので、JsonHandlerに改名したほうが良いでしょうか

**Comment by ecilavip** [comment]
確かに。任せます
